# Generated by Django 3.2.6 on 2022-09-04 10:47

import blango_auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blango_auth', '0002_auto_20220829_1654'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', blango_auth.models.BlangoUserManager()),
            ],
        ),
    ]
